=== SymphonyOfTranquility/OOP-3-course/lab2/candy.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Candies">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Candy" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string"/>
                            <xs:element name="Energy" type="xs:positiveInteger"/>

                            <xs:element name="Type">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="filling" type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="Ingredients">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Water" type="xs:positiveInteger" minOccurs="0"/>
                                        <xs:element name="Sugar" type="xs:positiveInteger" minOccurs="0"/>
                                        <xs:element name="Fructose" type="xs:positiveInteger" minOccurs="0"/>
                                        <xs:element name="ChocolateType" type="xs:string" minOccurs="0"/>
                                        <xs:element name="Vanilla" type="xs:positiveInteger" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="Value">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Proteins" type="xs:positiveInteger"/>
                                        <xs:element name="Fat" type="xs:positiveInteger"/>
                                        <xs:element name="Carbon" type="xs:positiveInteger"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="Production" type="xs:string"/>
                        </xs:sequence>

                        <xs:attribute name="id" type="xs:ID" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SymphonyOfTranquility/OOP-3-course/lab2/candyukr.xml
<?xml version="1.0" encoding="UTF-8"?>
<Candies xsi:schemaLocation="candy.xsd">

<Candy id="1">
    <Name>Слівкі лінівкі вафля</Name>
    <Energy>420</Energy>
    <Type filling="milk cream">Chocolate with filling</Type>

    <Ingredients>
        <Water>15</Water>
        <Sugar>30</Sugar>
        <ChocolateType>Black chocolate</ChocolateType>
        <Vanilla>5</Vanilla>
    </Ingredients>

    <Value>
        <Proteins>15</Proteins>
        <Fat>5</Fat>
        <Carbon>80</Carbon>
    </Value>

    <Production>Рошен</Production>
</Candy>


<Candy id="2">
    <Name>Джеллі</Name>
    <Energy>450</Energy>
    <Type>Jelly</Type>

    <Ingredients>
        <Water>30</Water>
        <Sugar>40</Sugar>
        <Fructose>15</Fructose>
        <Vanilla>10</Vanilla>
    </Ingredients>
    
    <Value>
        <Proteins>5</Proteins>
        <Fat>3</Fat>
        <Carbon>92</Carbon>
    </Value>

    <Production>Рошен</Production>
</Candy>


<Candy id="3">
    <Name>Капрі молоко</Name>
    <Energy>370</Energy>
    <Type>Caramel</Type>

    <Ingredients>
        <Water>20</Water>
        <Sugar>40</Sugar>
        <Vanilla>15</Vanilla>
    </Ingredients>

    <Value>
        <Proteins>20</Proteins>
        <Fat>10</Fat>
        <Carbon>70</Carbon>
    </Value>

    <Production>Рошен</Production>
</Candy>


<Candy id="4">
    <Name>Трюфель</Name>
    <Energy>440</Energy>
    <Type filling="chocolate cream">Chocolate with filling</Type>

    <Ingredients>
        <Water>15</Water>
        <Sugar>35</Sugar>
        <ChocolateType>Milk chocolate</ChocolateType>
        <Vanilla>5</Vanilla>
    </Ingredients>

    <Value>
        <Proteins>10</Proteins>
        <Fat>5</Fat>
        <Carbon>85</Carbon>
    </Value>

    <Production>Світоч</Production>
</Candy>


<Candy id="5">
    <Name>ФЛОРЕНС</Name>
    <Energy>480</Energy>
    <Type filling="chocolate cream with nut">Chocolate with filling</Type>

    <Ingredients>
        <Water>20</Water>
        <Sugar>45</Sugar>
        <ChocolateType>White chocolate</ChocolateType>
        <Vanilla>10</Vanilla>
    </Ingredients>

    <Value>
        <Proteins>3</Proteins>
        <Fat>1</Fat>
        <Carbon>96</Carbon>
    </Value>

    <Production>АВК</Production>
</Candy>

</Candies>

=== SymphonyOfTranquility/OOP-3-course/lab2/candy.xml
<?xml version="1.0" encoding="UTF-8"?>
<Candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="candy.xsd">

<Candy id="ID-1">
    <Name>Slivki linivki vaflya</Name>
    <Energy>420</Energy>
    <Type filling="milk cream">Chocolate with filling</Type>

    <Ingredients>
        <Water>15</Water>
        <Sugar>30</Sugar>
        <ChocolateType>Black chocolate</ChocolateType>
        <Vanilla>5</Vanilla>
    </Ingredients>

    <Value>
        <Proteins>15</Proteins>
        <Fat>5</Fat>
        <Carbon>80</Carbon>
    </Value>

    <Production>Roshen</Production>
</Candy>


<Candy id="ID-2">
    <Name>Jelly</Name>
    <Energy>450</Energy>
    <Type>Jelly</Type>

    <Ingredients>
        <Water>30</Water>
        <Sugar>40</Sugar>
        <Fructose>15</Fructose>
        <Vanilla>10</Vanilla>
    </Ingredients>
    
    <Value>
        <Proteins>5</Proteins>
        <Fat>3</Fat>
        <Carbon>92</Carbon>
    </Value>

    <Production>Roshen</Production>
</Candy>


<Candy id="ID-3">
    <Name>Kapri moloko</Name>
    <Energy>370</Energy>
    <Type>Caramel</Type>

    <Ingredients>
        <Water>20</Water>
        <Sugar>40</Sugar>
        <Vanilla>15</Vanilla>
    </Ingredients>

    <Value>
        <Proteins>20</Proteins>
        <Fat>10</Fat>
        <Carbon>70</Carbon>
    </Value>

    <Production>Roshen</Production>
</Candy>


<Candy id="ID-4">
    <Name>Truffle</Name>
    <Energy>440</Energy>
    <Type filling="chocolate cream">Chocolate with filling</Type>

    <Ingredients>
        <Water>15</Water>
        <Sugar>35</Sugar>
        <ChocolateType>Milk chocolate</ChocolateType>
        <Vanilla>5</Vanilla>
    </Ingredients>

    <Value>
        <Proteins>10</Proteins>
        <Fat>5</Fat>
        <Carbon>85</Carbon>
    </Value>

    <Production>Svitoch</Production>
</Candy>


<Candy id="ID-5">
    <Name>FLORENCE</Name>
    <Energy>480</Energy>
    <Type filling="chocolate cream with nut">Chocolate with filling</Type>

    <Ingredients>
        <Water>20</Water>
        <Sugar>45</Sugar>
        <ChocolateType>White chocolate</ChocolateType>
        <Vanilla>10</Vanilla>
    </Ingredients>

    <Value>
        <Proteins>3</Proteins>
        <Fat>1</Fat>
        <Carbon>96</Carbon>
    </Value>

    <Production>AVK</Production>
</Candy>

</Candies>
