=== SymphonyOfTranquility/OOP-3-course/lab2/paper.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Papers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Paper" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Title" type="xs:string"/>
                            <xs:element name="Type">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="newspaper"/>
                                        <xs:enumeration value="magazine"/>
                                        <xs:enumeration value="booklet"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="Monthly" type="xs:boolean"/>

                            <xs:element name="Chars">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Colored" type="xs:boolean"/>
                                        <xs:element name="Size" type="xs:positiveInteger"/>
                                        <xs:element name="Glossy" type="xs:boolean"/>
                                        <xs:element name="SubscriptionIndex" type="xs:boolean"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>

                        <xs:attribute name="id" type="xs:ID" use="required"/>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SymphonyOfTranquility/OOP-3-course/lab2/paper.xml
<?xml version="1.0" encoding="UTF-8"?>
<Papers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="paper.xsd">

    <Paper id="ID-1">
        <Title>Mriya</Title>
        <Type>newspaper</Type>
        <Monthly>true</Monthly>

        <Chars>
            <Colored>true</Colored>
            <Size>20</Size>
            <Glossy>false</Glossy>
            <SubscriptionIndex>true</SubscriptionIndex>
        </Chars>
    </Paper>


    <Paper id="ID-2">
        <Title>Vsesvit</Title>
        <Type>magazine</Type>
        <Monthly>true</Monthly>

        <Chars>
            <Colored>true</Colored>
            <Size>50</Size>
            <Glossy>true</Glossy>
            <SubscriptionIndex>true</SubscriptionIndex>
        </Chars>
    </Paper>


    <Paper id="ID-3">
        <Title>Visti</Title>
        <Type>newspaper</Type>
        <Monthly>false</Monthly>

        <Chars>
            <Colored>true</Colored>
            <Size>15</Size>
            <Glossy>false</Glossy>
            <SubscriptionIndex>true</SubscriptionIndex>
        </Chars>
    </Paper>


    <Paper id="ID-4">
        <Title>Borezil</Title>
        <Type>magazine</Type>
        <Monthly>true</Monthly>

        <Chars>
            <Colored>true</Colored>
            <Size>20</Size>
            <Glossy>false</Glossy>
            <SubscriptionIndex>true</SubscriptionIndex>
        </Chars>
    </Paper>


    <Paper id="ID-5">
        <Title>Ekologichni problemi</Title>
        <Type>booklet</Type>
        <Monthly>true</Monthly>

        <Chars>
            <Colored>true</Colored>
            <Size>20</Size>
            <Glossy>false</Glossy>
            <SubscriptionIndex>false</SubscriptionIndex>
        </Chars>
    </Paper>

</Papers>
